SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[IsCompletedCase](@id BIGINT)
RETURNS TINYINT
AS 
BEGIN
	RETURN(
			SELECT CASE WHEN COUNT(*)=0 THEN 0 ELSE 1 END FROM t_MES WHERE rf_idCase=@id
			)
END

GO
GRANT EXECUTE ON  [dbo].[IsCompletedCase] TO [db_AccountOMS]
GO
