SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[vw_ZAP]
as
SELECT N_ZAP, (SELECT ID_PAC FROM dbo.t_260order WHERE ID_PAC=t.ID_PAC FOR XML PATH('PACIENT'),TYPE) AS Pacient,
(SELECT IDCASE from dbo.t_260order  WHERE ID_PAC=t.ID_PAC FOR XML PATH('Z_SL'),TYPE) AS SLUCH
FROM dbo.t_260order t
GO
