SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE VIEW [dbo].[vw_Pacient260_ONK]
AS
SELECT DISTINCT id AS idFile,rf_idRecordCasePatient,N_ZAP,ID_PAC,VPOLIS
,CASE WHEN v.rf_idSMO<>'34' THEN '18000' ELSE NULL END AS ST_OKATO,SPOLIS,NPOLIS
		,CASE WHEN v.rf_idSMO<>'34' THEN v.rf_idSMO ELSE v.CodeSMO34 END AS SMO	
		,NOVOR, MONTH,YEAR 
FROM dbo.t_260order_ONK v



GO
