SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[vw_ZAP260_ONK]
AS
SELECT DISTINCT id AS idFile,rf_idRecordCasePatient,N_ZAP,IsNew AS PR_NOV,MONTH,YEAR FROM dbo.t_260order_ONK

GO
