SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[vw_Account260_VMP]
AS
SELECT DISTINCT id,CODE,CODE_MO,[YEAR],[MONTH],Account AS NSCHET, DateRegister AS DSCHET,CASE WHEN PLAT<>'34' THEN PLAT ELSE NULL END AS PLAT,SUMMAV
		,MONTH(Date_Z_2) AS ReportMonth
from dbo.t_260order_VMP


GO
