SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[vw_SL260_VMP]
AS
SELECT rf_idRecordCasePatient,rf_idCase,GUID_Case AS SL_ID,VID_HMP,METOD_HMP,PROFIL_K,rf_idV002 AS PROFIL,DET, TAL_D,TAL_NUM,TAL_P,NHISTORY,DATE_1,DATE_2,DS1
	,C_ZAB,DS_ONK, PRVS,VERS_SPEC,IDDOKT,Quantity AS ED_COL, TARIFF AS TARIF, SUM_M
from dbo.t_260order_VMP 
GO
