CREATE TABLE [dbo].[t_SendingDataIntoFFOMS]
(
[id_old] [bigint] NULL,
[rf_idCase] [bigint] NOT NULL,
[CodeM] [char] (6) COLLATE Cyrillic_General_CI_AS NOT NULL,
[rf_idMO] [char] (6) COLLATE Cyrillic_General_CI_AS NOT NULL,
[ReportMonth] [tinyint] NOT NULL,
[ReportYear] [smallint] NOT NULL,
[rf_idF008] [tinyint] NOT NULL,
[rf_idV006] [tinyint] NOT NULL,
[SeriaPolis] [varchar] (10) COLLATE Cyrillic_General_CI_AS NULL,
[NumberPolis] [varchar] (20) COLLATE Cyrillic_General_CI_AS NOT NULL,
[BirthDay] [date] NOT NULL,
[rf_idV005] [tinyint] NOT NULL,
[idRecordCase] [bigint] NOT NULL,
[rf_idV014] [tinyint] NULL,
[UnitOfHospital] [varchar] (20) COLLATE Cyrillic_General_CI_AS NULL,
[DateBegin] [date] NOT NULL,
[DateEnd] [date] NOT NULL,
[DS1] [char] (10) COLLATE Cyrillic_General_CI_AS NULL,
[DS2] [char] (10) COLLATE Cyrillic_General_CI_AS NULL,
[DS3] [char] (10) COLLATE Cyrillic_General_CI_AS NULL,
[rf_idV009] [smallint] NOT NULL,
[MES] [varchar] (20) COLLATE Cyrillic_General_CI_AS NULL,
[AmountPayment] [decimal] (15, 2) NOT NULL,
[AmountPaymentZSL] [decimal] (15, 2) NOT NULL,
[idMU] [varchar] (36) COLLATE Cyrillic_General_CI_AS NULL,
[MUSurgery] [varchar] (20) COLLATE Cyrillic_General_CI_AS NULL,
[Age] [smallint] NULL,
[VZST] [int] NOT NULL,
[K_KSG] [varchar] (20) COLLATE Cyrillic_General_CI_AS NULL,
[KSG_PG] [int] NOT NULL,
[PVT] [int] NOT NULL,
[IsDisableCheck] [int] NOT NULL,
[IsFullDoubleDate] [bit] NOT NULL,
[IsUnload] [bit] NOT NULL,
[IT_SL] [decimal] (3, 2) NULL,
[SL_K] [int] NOT NULL,
[ENP] [varchar] (16) COLLATE Cyrillic_General_CI_AS NULL,
[TypeCases] [tinyint] NOT NULL,
[Quantity] [int] NULL,
[TotalPriceMU] [decimal] (15, 2) NULL,
[UR_K] [tinyint] NULL,
[IDSP] [tinyint] NULL,
[NewValue] [tinyint] NOT NULL,
[id] [bigint] NULL,
[DateInsert] [smalldatetime] NOT NULL
) ON [PRIMARY]
GO
