CREATE TABLE [dbo].[t_DS_ONK_REAB]
(
[rf_idCase] [bigint] NOT NULL,
[DS_ONK] [tinyint] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_DS_ONK_IdCase] ON [dbo].[t_DS_ONK_REAB] ([DS_ONK]) INCLUDE ([rf_idCase]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_DSONK] ON [dbo].[t_DS_ONK_REAB] ([rf_idCase]) INCLUDE ([DS_ONK]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[t_DS_ONK_REAB] ADD CONSTRAINT [FK_t_DS_ONK_REAB_Cases] FOREIGN KEY ([rf_idCase]) REFERENCES [dbo].[t_Case] ([id]) ON DELETE CASCADE
GO
GRANT INSERT ON  [dbo].[t_DS_ONK_REAB] TO [db_AccountOMS]
GO
GRANT SELECT ON  [dbo].[t_DS_ONK_REAB] TO [db_AccountOMS]
GO
