CREATE TABLE [dbo].[MedicalCare]
(
[id] [bigint] NOT NULL,
[CODE_MO] [char] (6) COLLATE Cyrillic_General_CI_AS NOT NULL,
[NSCHET] [varchar] (15) COLLATE Cyrillic_General_CI_AS NULL,
[DateRegister] [date] NOT NULL,
[IDCASE] [bigint] NOT NULL,
[PLAT] [char] (5) COLLATE Cyrillic_General_CI_AS NULL,
[PR_NOV] [bit] NULL,
[NOVOR] [varchar] (9) COLLATE Cyrillic_General_CI_AS NOT NULL,
[Fam] [nvarchar] (40) COLLATE Cyrillic_General_CI_AS NULL,
[IM] [nvarchar] (40) COLLATE Cyrillic_General_CI_AS NULL,
[Ot] [nvarchar] (40) COLLATE Cyrillic_General_CI_AS NULL,
[DR] [date] NULL,
[W] [tinyint] NOT NULL,
[MR] [nvarchar] (100) COLLATE Cyrillic_General_CI_AS NULL,
[ENP] [varchar] (16) COLLATE Cyrillic_General_CI_AS NULL,
[USL_OK] [tinyint] NOT NULL,
[VIDPOM] [smallint] NOT NULL,
[FOR_POM] [tinyint] NULL,
[ISHOD] [smallint] NOT NULL,
[RSLT] [smallint] NOT NULL,
[SUMV] [decimal] (15, 2) NOT NULL,
[SL_ID] [uniqueidentifier] NOT NULL,
[PROFIL] [smallint] NOT NULL,
[NHISTORY] [nvarchar] (50) COLLATE Cyrillic_General_CI_AS NOT NULL,
[P_PER] [tinyint] NULL,
[DATE_1] [date] NOT NULL,
[DATE_2] [date] NOT NULL,
[DS1] [char] (10) COLLATE Cyrillic_General_CI_AS NULL,
[PRVS] [int] NOT NULL,
[IDDOKT] [varchar] (25) COLLATE Cyrillic_General_CI_AS NULL
) ON [PRIMARY]
GO
